"""Admin table

Revision ID: b3bdca93f3e0
Revises: 
Create Date: 2019-07-03 19:52:01.109357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bdca93f3e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('',
    sa.Column('column1', sa.NullType(), nullable=True),
    sa.Column('column2', sa.NullType(), nullable=True),
    sa.Column('column3', sa.NullType(), nullable=True),
    sa.Column('column4', sa.NullType(), nullable=True),
    sa.Column('column5', sa.NullType(), nullable=True),
    sa.Column('column6', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
